# Generated by Django 2.2.7 on 2019-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_actors',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_commingmovies',
            field=models.ManyToManyField(related_name='liked_users', to='movies.CommingMovie'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_directors',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Director'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_recommends',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Recommend'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='liked_users', to='movies.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
