# Generated by Django 2.2.7 on 2019-11-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commingmovie',
            name='post_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
