# Generated by Django 2.2.7 on 2019-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_commingmovie_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commingmovie',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
